### PR TITLE
Issue fixes and siddhi related version bumps

### LINKED ISSUE #9: Siddhi application always repeated start
**Description:**
I try to run siddhi application with the siddhi-sdk but ,I found that the siddhi-application will always repeated start-action.
This is the command-line when I started application:
F:/studySoftware/siddhi-sdk-1.0.0\bin\siddhi.bat run E:/CompanyProj/siddhiDemo/src/com/pop.siddhi

Here is the result :
```
[org.wso2.extension.siddhi.io.http.source.HttpConnectorPortBindingListener] : siddhi: started HTTP server connector localhost:8081
[org.wso2.extension.siddhi.io.http.source.HttpSourceListener] : Source Listener has created for url http://localhost:8081/Api/public/test
[org.wso2.extension.siddhi.io.http.source.HttpSourceListener] : Source Listener has created for url http://localhost:8081/Api/public/test
ERROR [org.wso2.siddhi.core.stream.input.source.Source] - Error on 'TestExecutSionPlan'. Listener URL http://localhost:8081/Api/public/test already connectedError while connecting at Source 'http' at 'FooStream'.
org.wso2.siddhi.core.exception.SiddhiAppCreationException: Error on 'TestExecutSionPlan'. Listener URL http://localhost:8081/Api/public/test already connected
	at org.wso2.extension.siddhi.io.http.source.HttpConnectorRegistry.registerSourceListener(HttpConnectorRegistry.java:143)

```
The bug info obviously show the problem,the application will start when it is already started
Also,I use the siddhi-io-kafka,the problem exist too.the log shows that the kafka-consumer will be created again and again.
So, I guess that this may be a bug
siddhi application source code:
```
@App:name('testSiddhi')

--@source(type='kafka',
--        topic.list='localtopic',
--        partition.no='1',
--        threading.option='single.thread',
--        group.id="test",
--        bootstrap.servers='localhost:9092',
--        @map(type='json'))
@source(type = 'http',
        receiver.url='http://localhost:8081/Api/public/test',
        basic.auth.enabled='false',@map(type='json'))
define stream FooStream (symbol string, price float, volume long);

--
--@sink(type='kafka',
--    topic='resulttopic',
--    partition.no='0',
--    bootstrap.servers='localhost:9092',
--    @map(type='json')
--)
@sink(type='log', prefix="LOGGER")
define stream OutputStream (symbol string, price float, volume long,multiple float);
@info(name = 'query1')
from FooStream select symbol, price, volume,(price * volume) as multiple  insert into OutputStream;
```
By the way,I also use Stream Processor Studio to test my code.it run successfully~

**Affected Product Version:**
Siddhi-SDK 1.0.0
**OS, DB, other environment details and versions:**    
Windows 10 , Idea Version: 2017.3.3 ,Siddhi-plugin-Idea 1.1.0
**Steps to reproduce:**
1. Write a siddhi code ,and run it with siddhi-sdk.......
Generally speaking~ I don't know how to describle the step to reproduce it .  There are normally step to run a application with siddhi-sdk.I strictly follow the guide to build it~

Thank you ~QvQ

### PR DESCRIPTION
**Pull request by RAVEENSR**
## Purpose
This PR resolves #9 and bumps siddhi and its extensions related versions. And also this adds siddhi.execution.env and siddhi.store.cassandra extensions.

## Goals
Fix siddhi sdk issues and add support to the latest siddhi version.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

**Review by grainier — APPROVED** [review]

File: modules/siddhi-launcher/src/main/java/org/wso2/siddhi/sdk/launcher/run/SiddhiRun.java [hunk 1]
```diff
@@ -37,24 +37,21 @@ public SiddhiRun() {
...
-                log.error("Internal Siddhi Error Occurred: " + e);
-                break;
+        try {
+            //Generating runtime
+            SiddhiAppRuntime siddhiAppRuntime = siddhiManager.createSiddhiAppRuntime(siddhiApp);
+
+            //Starting event processing
+            siddhiAppRuntime.start();
+
+            if (!(inputFile == null || inputFile.equalsIgnoreCase(""))) {
```
Comment (fazlan-nazeem) [inline modules/siddhi-launcher/src/main/java/org/wso2/siddhi/sdk/launcher/run/SiddhiRun.java:47]: Should rather use StringUtils.isEmpty if the dependency is available. It's more readable.

Comment (RAVEENSR) [reply modules/siddhi-launcher/src/main/java/org/wso2/siddhi/sdk/launcher/run/SiddhiRun.java:47]: Usually, all the siddhi related repositories do not have org.apache.commons.lang3 dependency. Hence followed this way.
